### ISSUE TITLE
Two ideas to improve performance

### ISSUE THREAD

**Issue by pokornyv** [josefkaufmann/ana_cont#15]
Dear developers,

  recently I modified the ana_cont package to calculate the deconvolution of surface density of states from differential conductance data measured using superconducting STM tip (see supplement of arXiv:2408.05115 for details). During the modifications, I found two ways to speed up the calculation that you might consider worth implementing:

1. setting `optimize=True` in `np.einsum()` in `solvers.py` while calculating `W2`, `M2`, `Evi` and `d2chi2` matrices speeds up significantly (up to 5x on my PC) the matrix operations without any lose of precision.

2. `W3` and `M3` matrices are not stored in C order. Corrrecting the order speeds up significantly the performance of `compute_f_J_diag` and `compute_f_J_offdiag` functions.

```
self.W3 = np.array(self.W2[:, None, :] * (self.V_svd[None, :, :]).transpose((0, 2, 1)),order='C')
self.M3 = np.array(self.M2[:, None, :] * (self.V_svd[None, :, :]).transpose((0, 2, 1)),order='C')
```

**Comment by josefkaufmann** [comment]
Dear Vladislav,

I apologize for taking such a long time to respond. Thank you very much for your great suggestions. 
The speed-up of solver initialization due to Einsum optimization was up to 20x for rather large grids. Correcting the array order led to a speed-up of about 2x for the whole continuation process. 

Your suggestions are implemented in pull request #18 and already merged.
