### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by zpsun-hubu** [josefkaufmann/ana_cont#5]
When I compiled this program with this command "python setup.py build_ext --inplace" on Windows Platform, there came out an error " ValueError: path 'ana_cont/' cannot end with '/' ". I don't know how to deal with this problem. 

![error02_LI](https://user-images.githubusercontent.com/83748306/120881139-b3476680-c601-11eb-89f7-f45c32998582.jpg)
![error01](https://user-images.githubusercontent.com/83748306/120881141-b3dffd00-c601-11eb-950b-ea7a0821171f.png)

**Comment by josefkaufmann** [comment]
The reason for this issue is that Windows uses '\' for file paths, whereas other platforms use '/'. 
As a first try, you can remove the slashes in line 14 of setup.py, that's probably the immediate source of the problem. However the library has been used only under Linux so far, and unfortunately I currently don't have access to a Windows system.

Please let me know how it goes.

**Comment by zpsun-hubu** [comment]
A link error occurs.
        LINK : fatal error LNK1181: can't open input file “m.lib”

Is it necessary or should it be replaced by other libraries for Windows system?

**Comment by josefkaufmann** [comment]
This is the C Math library. I am not sure how to access it under Windows. 
If you find a way to make it work, I would be happy if you posted your solution here. 

Just a comment: In case you want to use Maxent, you don't need to compile at all. The compilation is only for the Pade module.

**Comment by zpsun-hubu** [comment]
After removing line 14 and "m.lib", the notebook "tutorial_svo" is passed.

**Comment by josefkaufmann** [comment]
That is nice to hear, thank you for the feedback!
